// <auto-generated />
using System;
using Gerenciado_de_Usuario_Papido_Facil.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerenciado_de_Usuario_Papido_Facil.Infra.Migrations
{
    [DbContext(typeof(GerenciadorUsuarioDbContext))]
    [Migration("20260209005855_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.CND", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoControle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRejeicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<Guid>("IdoneidadeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdoneidadeId");

                    b.ToTable("CND");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.CNDT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExpedicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRejeicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<Guid>("IdoneidadeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NumeroCertidao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdoneidadeId");

                    b.ToTable("CNDT");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CondominioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CondominoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmpresaPrestadoraId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AceitouTermosDeUso")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoVinculacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PeriodoTeste")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PorteCondominio")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Condominio");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condomino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AceitouTermosDeUso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apartamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoVinculacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CondominioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PlanoValido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Vinculado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Condomino");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AceitouTermosDeUso")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("EmpresaPrestadora");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadoraServicoSubtipo", b =>
                {
                    b.Property<Guid>("EmpresaPrestadoraId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicoSubtipoId")
                        .HasColumnType("char(36)");

                    b.HasKey("EmpresaPrestadoraId", "ServicoId", "ServicoSubtipoId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("ServicoSubtipoId");

                    b.ToTable("EmpresaPrestadoraServicos");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Idoneidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataUltimaAnalise")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EIdoneidade")
                        .HasColumnType("int");

                    b.Property<Guid>("EmpresaPrestadoraId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Idoneo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaPrestadoraId");

                    b.ToTable("Idoneidade");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.MensagemChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("MensagemChat");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FoiLido")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("IdRelacionado")
                        .HasColumnType("char(36)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Notificacao");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.ToTable("ServicoSubtipos");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.TemplateHTML", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TemplateHTML", (string)null);
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.CND", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Idoneidade", null)
                        .WithMany("CND")
                        .HasForeignKey("IdoneidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.CNDT", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Idoneidade", null)
                        .WithMany("CNDT")
                        .HasForeignKey("IdoneidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condomino", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condominio", null)
                        .WithMany("Condominos")
                        .HasForeignKey("CondominioId");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadoraServicoSubtipo", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", "EmpresaPrestadora")
                        .WithMany("EmpresaPrestadoraServicoSubtipos")
                        .HasForeignKey("EmpresaPrestadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", "Servico")
                        .WithMany("EmpresaPrestadoraServicos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", "ServicoSubtipo")
                        .WithMany("EmpresaPrestadoraServicoSubtipos")
                        .HasForeignKey("ServicoSubtipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaPrestadora");

                    b.Navigation("Servico");

                    b.Navigation("ServicoSubtipo");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Idoneidade", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", "EmpresaPrestadora")
                        .WithMany()
                        .HasForeignKey("EmpresaPrestadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaPrestadora");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.MensagemChat", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Chat", "Chat")
                        .WithMany("mensagens")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", b =>
                {
                    b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", null)
                        .WithMany("ServicoSubtipos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Chat", b =>
                {
                    b.Navigation("mensagens");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condominio", b =>
                {
                    b.Navigation("Condominos");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", b =>
                {
                    b.Navigation("EmpresaPrestadoraServicoSubtipos");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Idoneidade", b =>
                {
                    b.Navigation("CND");

                    b.Navigation("CNDT");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", b =>
                {
                    b.Navigation("EmpresaPrestadoraServicos");

                    b.Navigation("ServicoSubtipos");
                });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", b =>
                {
                    b.Navigation("EmpresaPrestadoraServicoSubtipos");
                });
#pragma warning restore 612, 618
        }
    }
}
