// <auto-generated />
using Gerenciado_de_Usuario_Rapido_Facil.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace Gerenciado_de_Usuario_Rapido_Facil.Infra.Migrations
{
    [DbContext(typeof(GerenciadorUsuarioDbContext))]
    [Migration("20241019171526_CreateCopiaServicoSubtipoParaCotacaoProcedure")]
    partial class CreateCopiaServicoSubtipoParaCotacaoProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condominio", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<bool>("Ativo")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("CnpjCpf")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("CodigoVinculacao")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Rua")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Condominio");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condomino", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<bool>("Ativo")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("CnpjCpf")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("CodigoVinculacao")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<Guid?>("CondominioId")
                    .HasColumnType("char(36)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Rua")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<bool>("Vinculado")
                    .HasColumnType("tinyint(1)");

                b.HasKey("Id");

                b.HasIndex("CondominioId");

                b.ToTable("Condomino");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<bool>("Ativo")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Bairro")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Cidade")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("CnpjCpf")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Logo")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Rua")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("EmpresaPrestadora");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadoraServicoSubtipo", b =>
            {
                b.Property<Guid>("EmpresaPrestadoraId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("ServicoId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("ServicoSubtipoId")
                    .HasColumnType("char(36)");

                b.HasKey("EmpresaPrestadoraId", "ServicoId", "ServicoSubtipoId");

                b.HasIndex("ServicoId");

                b.HasIndex("ServicoSubtipoId");

                b.ToTable("EmpresaPrestadoraServicos");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Servicos");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<Guid>("ServicoId")
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.HasIndex("ServicoId");

                b.ToTable("ServicoSubtipos");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condomino", b =>
            {
                b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condominio", null)
                    .WithMany("Condominos")
                    .HasForeignKey("CondominioId");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadoraServicoSubtipo", b =>
            {
                b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", "EmpresaPrestadora")
                    .WithMany("EmpresaPrestadoraServicoSubtipos")
                    .HasForeignKey("EmpresaPrestadoraId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", "Servico")
                    .WithMany("EmpresaPrestadoraServicos")
                    .HasForeignKey("ServicoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", "ServicoSubtipo")
                    .WithMany("EmpresaPrestadoraServicoSubtipos")
                    .HasForeignKey("ServicoSubtipoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("EmpresaPrestadora");

                b.Navigation("Servico");

                b.Navigation("ServicoSubtipo");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", b =>
            {
                b.HasOne("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", null)
                    .WithMany("ServicoSubtipos")
                    .HasForeignKey("ServicoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Condominio", b =>
            {
                b.Navigation("Condominos");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.EmpresaPrestadora", b =>
            {
                b.Navigation("EmpresaPrestadoraServicoSubtipos");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.Servico", b =>
            {
                b.Navigation("EmpresaPrestadoraServicos");

                b.Navigation("ServicoSubtipos");
            });

            modelBuilder.Entity("Gerenciado_de_Usuario_Papido_Facil.Domain.Entities.ServicoSubtipo", b =>
            {
                b.Navigation("EmpresaPrestadoraServicoSubtipos");
            });
#pragma warning restore 612, 618
        }
    }
}